export {
  iconConfigSchema,
  headerConfigSchema,
  messageConfigSchema,
  avatarConfigSchema,
  inputConfigSchema,
  sendButtonConfigSchema,
  bodyConfigSchema,
  bubbleConfigSchema,
  typographyConfigSchema,
  animationsConfigSchema,
  timestampsConfigSchema,
  starterSchema,
  startersConfigSchema,
  brandingConfigSchema,
  widgetThemeSchema,
  partialWidgetThemeSchema,
  defaultWidgetTheme,
} from '@repo/validation';

export type {
  IconConfig,
  HeaderConfig,
  MessageConfig,
  AvatarConfig,
  InputConfig,
  SendButtonConfig,
  BodyConfig,
  BubbleConfig,
  TypographyConfig,
  AnimationsConfig,
  TimestampsConfig,
  Starter,
  StartersConfig,
  BrandingConfig,
  WidgetTheme,
  PartialWidgetTheme,
} from '@repo/validation';
